spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres-order-db:5432/order_db
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true